# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180202_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
